# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{required}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = %q{2010-06-29}
  s.description = %q{DSL to facilitate require/load of ruby files and folders}
  s.email = %q{kmandrup@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "lib/required.rb",
     "spec/.rspec",
     "spec/required/except_also_me.rb",
     "spec/required/except_me.rb",
     "spec/required/not_me.erb.rb",
     "spec/required/not_this_folder/sub_not_me.rb",
     "spec/required/only_me.rb",
     "spec/required/required_spec.rb",
     "spec/required/this_folder/subsub/a_sub_sub_file.rb",
     "spec/required/this_folder/yes_me.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/kristianmandrup/required}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{DSL to facilitate require/load of ruby files and folders}
  s.test_files = [
    "spec/required/except_also_me.rb",
     "spec/required/except_me.rb",
     "spec/required/not_me.erb.rb",
     "spec/required/not_this_folder/sub_not_me.rb",
     "spec/required/only_me.rb",
     "spec/required/required_spec.rb",
     "spec/required/this_folder/subsub/a_sub_sub_file.rb",
     "spec/required/this_folder/yes_me.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 2.0.0.beta.14"])
    else
      s.add_dependency(%q<rspec>, [">= 2.0.0.beta.14"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 2.0.0.beta.14"])
  end
end

